export const LINKEDIN_ACTION_TYPES = {
  SEND_CONNECTION_REQUEST: 'SEND_CONNECTION_REQUEST',
  SEND_MESSAGE: 'SEND_MESSAGE',
  WITHDRAW_CONNECTION_REQUEST: 'WITHDRAW_CONNECTION_REQUEST',
} as const;

export type LinkedInActionType =
  (typeof LINKEDIN_ACTION_TYPES)[keyof typeof LINKEDIN_ACTION_TYPES];

export const LINKEDIN_ACTION_STATUSES = {
  SCHEDULED: 'SCHEDULED',
  CLAIMED: 'CLAIMED',
  COMPLETED: 'COMPLETED',
  SKIPPED: 'SKIPPED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export type LinkedInActionStatus =
  (typeof LINKEDIN_ACTION_STATUSES)[keyof typeof LINKEDIN_ACTION_STATUSES];

export const LINKEDIN_CONNECTION_STATES = {
  UNKNOWN: 'UNKNOWN',
  NOT_CONNECTED: 'NOT_CONNECTED',
  PENDING: 'PENDING',
  CONNECTED: 'CONNECTED',
  WITHDRAWN: 'WITHDRAWN',
} as const;

export type LinkedInConnectionState =
  (typeof LINKEDIN_CONNECTION_STATES)[keyof typeof LINKEDIN_CONNECTION_STATES];
